apiVersion: apps/v1
kind: Deployment
metadata:
  run: myapp
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      run: myapp
  template:
    metadata:
      labels:
        run: myapp
    spec:
      containers:
      - name: myapp
        image: docker pull gcr.io/abacus-mean/daniel-choi-158/mean-webapp-frontend-angular:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4200
